version: '3'

services:
  flask-app-1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"

  flask-app-2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
